// <auto-generated />
using EMovies.Modules.Reviews.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EMovies.Modules.Reviews.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ReviewsDbContext))]
[Migration("20260726005436_InitialReviews")]
partial class InitialReviews
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("reviews")
            .HasAnnotation("ProductVersion", "10.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("EMovies.Modules.Reviews.Domain.Review", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<string>("Content")
                .HasMaxLength(4000)
                .HasColumnType("character varying(4000)");

            b.Property<DateTime>("CreatedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTime?>("ModeratedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("ModerationReason")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)");

            b.Property<Guid>("MovieId")
                .HasColumnType("uuid");

            b.Property<int>("Rating")
                .HasColumnType("integer");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnType("character varying(20)");

            b.Property<DateTime>("UpdatedAtUtc")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("UserDisplayName")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<string>("UserId")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.HasKey("Id");
            b.HasIndex("MovieId", "Status");
            b.HasIndex("MovieId", "UserId")
                .IsUnique();

            b.ToTable("reviews", "reviews", table =>
            {
                table.HasCheckConstraint(
                    "CK_reviews_rating",
                    "\"Rating\" BETWEEN 1 AND 5");
            });
        });
#pragma warning restore 612, 618
    }
}
